### ISSUE TITLE
g add_defines

### ISSUE THREAD

**Issue by k06a** [CocoaPods/Core#366] opened 2017-01-16 18:56 UTC

**Comment by segiddins** [comment] 2017-01-16 19:07
Closing because the issue is empty.

**Closed by segiddins** 2017-01-16 19:07 UTC

**Comment by k06a** [comment] 2017-01-17 07:58
@segiddins sorry, maybe my baby opened this issue 🙃

![ezgif com-optimize-2](https://cloud.githubusercontent.com/assets/702124/22012129/a45da59a-dca3-11e6-9224-f117beeb9e0c.gif)
