### ISSUE TITLE
[Bug] Dependencies of Target B Linking to Target A in a Two Target Project

### ISSUE THREAD

**Issue by DeclanMcPartlin** [CocoaPods/Core#715] opened 2022-02-17 22:16 UTC
[X ] I've read and understood the [CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
## What did you do?
I installed cocoapod dependencies for a two target system. Target A has a dependency on Target B. I set the linking as dynamic with use_frameworks!. Target A's list of dependencies is empty. Target B has a list of dependencies.

### Extra Insight
[Here is an example project underlining the problem](https://github.com/DeclanMcPartlin/MultiTargetCocoapodIssue/tree/master/CocoaPodsMultiTargetIssue). This is a simple Xcode project where Target A is an application target, and Target B is a framework target. Target B is a dependency of Target A. This is in fact a very common setup, due to the fact that all generated Unity projects have this structure for example.

## What did you expect to happen?
The dependencies will only be added to the OTHER_LDFLAGS of Target B.

## What happened instead?
The dependencies are also added to the OTHER_LDFLAGS of Target A. This results in classes being included in both targets, resulting in a long list of issues with a similar format to this:
```
objc[4056]: Class ADCClickOverride is implemented in both /private/var/containers/Bundle/Application/FF0023B5-B3EC-4E0D-B4E7-65D5B08A73D9/TargetA.app/Frameworks/TargetB.framework/TargetB (0x106c447c0) and /private/var/containers/Bundle/Application/FF0023B5-B3EC-4E0D-B4E7-65D5B08A73D9/TargetA.app/TargetA (0x1054ba698). One of the two will be used. Which one is undefined.
//Repeats for each class, it is a long list in this case.
```

Other outcomes [are documented here](https://github.com/DeclanMcPartlin/MultiTargetCocoapodIssue/blob/71be5a28059a4093008e7c32800654dafea6dd75/CocoaPodsMultiTargetIssue/Podfile#L74), with the Podfile setup provided just above each resulting outcome.

Currently we are required to use [this script](https://github.com/DeclanMcPartlin/MultiTargetCocoapodIssue/blob/71be5a28059a4093008e7c32800654dafea6dd75/CocoaPodsMultiTargetIssue/Podfile#L21) to remove the dependencies from OTHER_LDFlAGS of Target A.

### A Potential Solution Proposal
A proposal we share here provides the user with a flag to state if the dependencies of the other target(s) should be linked or not. [Here are the changes proposed for Cocoapods/Core](https://github.com/CocoaPods/Core/commit/1950aa833e0f07d8d58b17fc468ed0cb7fb9d91e), and [here are the changes for Cocoapods/Cocoapods](https://github.com/CocoaPods/CocoaPods/compare/master...serge-14:feature/do_not_link_pods).

The question we are asking ourselves though, is if this is expected behaviour? Should such linking happen at all, and if so, what is the use case? If there is no use case, then ideally such linking shouldn't happen by default.

Thanks for reading this 👍 

## CocoaPods Environment
Happened with cocoapod 1.11.2

**Comment by dnkoutso** [comment] 2022-03-11 17:03
This seems like a duplicate of https://github.com/CocoaPods/CocoaPods/issues/11231.

It seems to better belong to CocoaPods rather than CocoaPods/Core because Core does not do any integration/wiring.

**Closed by dnkoutso** 2022-03-11 17:03 UTC
