### ISSUE TITLE
pod setup does not recognize the git repo

### ISSUE THREAD

**Issue by msaelices** [CocoaPods/Core#446] opened 2018-04-17 23:55 UTC
Steps for reproduce the error: simply execute `pod setup` twice. The first one it create the master git repo to the cocoa specs. The second one raises the following error:
```
$ pod setup
Setting up CocoaPods master repo
env: illegal option -- u
usage: env [-i] [name=value ...] [utility [argument ...]]
[!] The `master` repo is not a git repo.
```

This is due to the `env -u GIT_CONFIG` part in [this line](https://github.com/CocoaPods/Core/blob/f0227968b79ce920657afcbadf7b141dd76b267a/lib/cocoapods-core/source.rb#L446), which makes command fail as is it mentioned [here](https://stackoverflow.com/questions/22623563/how-to-unset-env-variable-on-os-x)

I'm newbie on MacOs development, but I cannot understand how this line could work in a MacOS environment, if the `env --unset` option is not supported.

**Comment by segiddins** [comment] 2018-04-18 00:04
cc @keith

**Comment by keith** [comment] 2018-04-18 00:06
Huh. What version of macOS are you using? I wasn't under the impression that this was a new flag

**Comment by DanToml** [comment] 2018-04-18 18:13
@keith The general rule for this is "Whatever current Xcode - 1 supports".

**Comment by keith** [comment] 2018-04-18 18:17
Well I can confirm 10.12 has `-u` support https://opensource.apple.com/source/shell_cmds/shell_cmds-198/env/env.c.auto.html

But if we want we can add an OS version check to this, since this is an edge case anyways.

**Comment by DanToml** [comment] 2018-04-19 17:04
I'd be ok with omitting that when not on >= 10.12 - I think Xcode 8.0 supported 10.11?

**Comment by keith** [comment] 2018-04-19 17:59
Sorry I wasn't exhaustive, 10.11 supports this as well. It appears that was the first version that added `-u`

**Comment by amamam2** [comment] 2018-04-28 02:14
393390

**Comment by Zyrix** [comment] 2018-10-25 11:56
Is there a way to use it on 10.10.5 or do you have to upgrade to 10.11?

**Comment by dantoml** [comment] 2019-02-14 22:54
Closing this issue because current Xcode versions do not support any macOS release without `env --unset`

**Closed by dantoml** 2019-02-14 22:54 UTC

**Comment by segiddins** [comment] 2019-02-14 23:19
Also, I removed the usage of `env -u` yesterday :D (now using posix spawn to unset the variable)
